{% set version = "3.0.2.post1" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyshp/pyshp-{{ version }}.tar.gz
  sha256: 18e34a66759b6d34a6f535978c76dad518200f23a727d9e22af8e8535c0245b9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python

test:
  imports:
    - shapefile
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/pyshp/
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format
  description: |
    The Python Shapefile Library (PyShp) reads and writes ESRI Shapefiles in pure Python.
  dev_url: https://github.com/GeospatialPython/pyshp
  doc_url: https://github.com/GeospatialPython/pyshp

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
