{% set name = "pyshp" %}
{% set version = "3.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81baf3f8a270015242576d9c90b9120d4a91719fda28d0d39a716b9ca99a4402

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python

# Passed locally but failed randomly on the build platform:
# E   shapefile.ShapefileException: Shapefile Reader requires a shapefile or file-like object. (no dbf file found)
{% set deselect_tests = " --deselect=test_shapefile.py::test_reader_url" %}
test:
  source_files:
    - tests
  imports:
    - shapefile
  commands:
    - pip check
    - python -m pytest -v tests/test_shapefile.py {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/pyshp
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format
  description: |
    The Python Shapefile Library (PyShp) reads and writes ESRI Shapefiles in pure Python.
  dev_url: https://github.com/GeospatialPython/pyshp
  doc_url: https://github.com/GeospatialPython/pyshp

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
