{% set version = "2.1.1" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyshp/pyshp-{{ version }}.tar.gz
  sha256: 0c317dbce9e1470310ce774a57b0dd0c69e55b2eae8673e9ac74aeed49f976e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - shapefile

about:
  home: https://pypi.python.org/pypi/pyshp
  license: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
