{% set version = "1.2.11" %}

package:
  name: pyshp
  version: {{ version }}

source:
  fn: pyshp-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pyshp/pyshp-{{ version }}.tar.gz
  sha256: 8b4be2ec3d816067972e9ecc38526e9c45e9ee9b49b7fd94acfab9c0fc84fa63

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - shapefile

about:
  home: https://pypi.python.org/pypi/pyshp
  license: MIT
  license_file: LICENSE.TXT
  summary: 'Pure Python read/write support for ESRI Shapefile format.'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
