{% set version = "2.3.1" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyshp/pyshp-{{ version }}.tar.gz
  sha256: 4caec82fd8dd096feba8217858068bacb2a3b5950f43c048c6dc32a3489d5af1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - shapefile
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/pyshp/
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format
  description: |
    The Python Shapefile Library (PyShp) reads and writes ESRI Shapefiles in pure Python.
  dev_url: https://github.com/GeospatialPython/pyshp
  doc_url: https://github.com/GeospatialPython/pyshp

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
