travis:
  secure:
    BINSTAR_TOKEN: REpOmKHV0tDQti1Fw+BOBavtpZhyVgXE9B696l7ChgDiY3xBbtV6Vkx7gsMWXI8FaD/Jf+6YRVD1Nc2EzOr+0qpF5EEKi632GjKwP+Sx5NSDUImN4dKApNEaCG5vOUxuh1deLfX1W2Rp7ZsiaNlJtxFqb0lreKTg/mT8IgCLwVe+25cGbVFa9Emlc6Vb0WBIvXAqfQKzHaixo5ImLQsguUjF7wXMIjIRLyMW1CL0stI5yOHkciqxIFC9+vPZSsdnQZ85hOpDLP5h6CjgImi09y3FNhgWGRWs3gSvbLsBnoGER5Akh2cAYCXtW9mnNsy9G7FMtrLxNM+O3z3d9bh/mR2zPFgXYQyvJyiOLKY6efA96p4V/5OzQVkKL7t7lC4qNGjJTmh3pswXZ1On7/erJTLzMtr2FhQ2lpDyZuEPGDPBhXQAncPRBoAGtF31EcDb9xfFwgvlWoOLvv7jI4tVSKWeEm+opW2HdW2MaB16QIHe6V1JCbyXaWz5xrp0pXYiCR9I/xaYj36d88oTutrxLbIkQ6m6gd624PmE5vZLjNBtJlsaoCCKekK0eATpMrcMmAGMk4L7OagMAoDYAIeiIuRrrLaGCV656VWbpAvj0gR8tYcrNtF8a7rIEvV7uwX3rKeqaB6HAxdr9r4uJ2Kf5COKt9uu61wTvXRANyeR1Gk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
