travis:
  secure:
    BINSTAR_TOKEN: E5dcMlYG+1BzvcJKu2qNtXdfmUJ0FLX1YhEPfPUrKzDOIQxm7E4Wn7sqwx8olWtUutvvZvYgYwDaYM9qgTcwNbBi3W6bXhIEaDENRgWWWCuuniuFU2CtJCIAPDARjJMGBJtTsNp0V9QdFep62yFHTxNJKN7RyhnxYMJbbcYB0YjRu4W/eKVOzuXLx90/2Vbocj7uxKSMg/kRLMuHTHWPLrRodDrGHwfNW39pnCtFMrRCSy/8Qq7+SCl+3/klF9A/+BQxuInyoDZ6gPOGFPq0X+aHvMdaYIplkSnSonBnmE7WcV2/Fd6y3oQ7R/+WK0nje9/iA52YMPmwb5Vdvm0dNK+YdJ8lcPOx8cURDovfwR2EnPf5x0pBLzMsQxR4Y8cKuqSyKvXrIaywqnUv7fYv9lXUC7x4SKr451WX9NfyO8mNytL7Al2yWfUPP0dBaHglMcM2V3gIsytHcwniFmyuJnDB2ohV/ShWln5uKnVoCROsSxy+jOYhafNe5euVF0JDZcqu4yaUMr5wGE7uR6ZcfYglysTLiQE+HZvqbtBlH1tJLWvMKF19Sk9oOpt2rX/ym8BEsYCvupc723o8Al4WqvGP2ehwk3/GhQDFeNbTjWgeffFmFq1pD2knZlBmI/rMJa1hNuDUeNjU3e6zQYz6Ryhr9k3OfBrcSemjXCmNnQw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
