travis:
  secure:
    BINSTAR_TOKEN: snEv+39HA8sh1OyYvSOCKQaAN6R8AxyW0kpsYg99RccM8giGkR8/FxomGTlkqTlCBLhN4CCbk1uCMrZG7JQoO/aHisD7vgvTrl9PhY+42RU8GoEcnsQ/OwdcVv7fdx1kPjZK17wnRejyKwGi4ismLG4K6zeUYgoVlJjSYJTNqFE5GSHvubdsArQ9bLY8QUpgAQYEjLCMWVJufbyEynivWUYIJeU4WgPX9talFwo3pZtzv0qRju3uKIYGmPJ0AS7J09ogfbpcl15QRFgTQ7tcUm/O1GxH3pZpR4S1kTTFsmTAXEW9IeunLH/hYCMTUyAr5c8y5hmJRmjsUIZ+xqEaQRhPY0VVLOmmPFwtROhMJW6+ge9+vf1EhadGL43ERKoxT9DsN9MnAQX0wWavHBNSGU/+Mdb4iuM0s1OSqfRvtapBaZA735le25bsCwpQnIg73oMLIFEFukbd9RvBVYrRRxvhOWb/DYdIzVHc/t4GayCNiIrK44C5RwgW6Qy5arnCWxqRUsIzvRlhVe2TXfnRFqjers81e/9aD+ehBbNGz0FNdI6adZCvg2Gij1/558PLTNWUOIqOvKxD6KZoDo+oYJKdQdTJtgeI24zjY4Lks7G3oflRGGGtOW860by777Fw37NmItBSdJmGTJtlggf5ayXGsqJNlGbj1VDlvwklRrw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
